#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Requirements:
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script
# Make sure that your servers are configured with the right hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02. If not, follow this tutorial.
# For your answer file, write a Bash script that configures a new Ubuntu machine to respect above requirements
sudo apt-get -y update
sudo apt-get install -y haproxy
sudo chmod 777 /etc/haproxy/haproxy.cfg
echo "listen firstbalance" >> /etc/haproxy/haproxy.cfg
echo "  bind *:80" >> /etc/haproxy/haproxy.cfg
echo "  server 4592-web-01 54.242.220.107:80 $CHECK" >> /etc/haproxy/haproxy.cfg
echo "  server 4592-web-02 54.211.63.59:80 $CHECK" >> /etc/haproxy/haproxy.cfg
sudoservice haproxy restart
