#!/usr/bin/env bash
# use the while that display "Best School" 10 times
counter=1
while [ $counter -le 10 ]
do
	if [ "$counter" == 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	(( counter++ ))
done
