#!/usr/bin/env bash
# Gives you information about the school file  
filename="school"
if [ -f "$filename" ] | [ -d "$filename" ]
then
	echo "$filename file exists"
	if [ -s "$filename" ]
	then
		echo "$filename file is not empty"
	else
		echo "$filename file is empty"
	fi
	if test -f "$filename"
	then
		echo "$filename is a regular file"
	fi
else
	echo "$filename file does not exist"
fi
